### ISSUE TITLE
Pre-built binary for Linux64 doesn't start on CentOS 7 x64

### ISSUE THREAD

**Issue by justinclift** [SaschaWillems/VulkanCapsViewer#57]
Just tried running the prebuilt binary for Linux 64 (1.92), on CentOS 7 (1810).  It fails with:

```
$ ./vulkanCapsViewer 
./vulkanCapsViewer: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./vulkanCapsViewer)
$
```

Tried compiling (using the `master` branch), but that's also failing:

```
$ qmake vulkanCapsViewer.pro
$ make
../../Qt/5.11.3/gcc_64/include/QtCore/qvariant.h:207:5: note:   no known conversion for argument 1 from ‘uint64_t {aka long unsigned int}’ to ‘QVariant::Type’
In file included from vulkancapsviewer.h:14:0,
                 from main.cpp:1:
vulkanDeviceInfo.hpp:596:92: error: call of overloaded ‘QVariant(uint64_t&)’ is ambiguous
             pushProperty2(extension, "maxInstanceCount", QVariant(extProps.maxInstanceCount));
```

That's with Qt 5.11.3, though the same error occurs with Qt 5.12.0.

Any ideas?

**Comment by SaschaWillems** [comment]
I just merged PR #55 that should fix the ambiguous overload error. Can you try again with those changes?

**Comment by justinclift** [comment]
Just looked at the PR you merged, and the fix for the errors seems super simple.  eg a missing cast.

So, just copied-n-pasted the same approach for the further two error locations, which let the build succeed.  Made a PR from it (https://github.com/SaschaWillems/VulkanCapsViewer/pull/58), in case it's useful.

Out of curiosity, the build still throws out many warnings.  They seem (at least mostly) to be `missing initializer for member`:

```
GeneratedFiles/release/../../vulkanDeviceInfo.hpp:988:66: warning: missing initializer for member ‘VkPhysicalDeviceFeatures2::sType’ [-Wmissing-field-initializers]
                     VkPhysicalDeviceFeatures2KHR deviceFeatures2{};
```

Is that something worth looking into?

The (old, default system) gcc that comes with CentOS 7 1810 is:

```
$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ which gcc
/usr/bin/gcc
```

So, not exactly gcc 8. :wink:

**Comment by SaschaWillems** [comment]
> Guessing the PR missing a spot or two?

Those lines were added after the initial PR. I mainly develop on windows using the MSVC compiler and that just compiles fine, so I tend to miss these from time to time ;)

> Is that something worth looking into?

Not really. It's intentional. I only initialize the structure type member of, the remaining members are not important, so that warning can be ignored.

P.S. : Thx for the PR and checking this out on Linux. I only built on Linux once in a while when doing new releases.

**Comment by justinclift** [comment]
No worries.  Should I try compiling on macOS too?  We have an old Mac Mini that sits around doing nothing but the nightly builds for [DB Browser for SQLite](https://github.com/sqlitebrowser/sqlitebrowser/).

Can git clone this repo to that and see how it goes, if that'd be useful. :smile:

**Comment by justinclift** [comment]
... and just realised thats a dumb question, as macOS doesn't seem to have Vulkan support anyway. :wink:

**Comment by SaschaWillems** [comment]
Actually that's in no way dumb ;)

Thanks to [MoltenVK](https://github.com/KhronosGroup/MoltenVK) it's possible to run Vulkan applications on MacOS and iOS.

Though I',m not sure if the current code base is properly working on Mac devices.

**Comment by justinclift** [comment]
Oh, interesting.  Looking at that project, it eventually leads through to macOS downloads:

&nbsp; &nbsp; https://vulkan.lunarg.com/sdk/home#mac

I'll see they install ok on our old build server, and if they do I'll try out compiling then running VulkanCapsViewer on it, just to see what happens. :smile:

**Comment by justinclift** [comment]
Doesn't seem like this is going to be feasible.  Probably more to do with the setup here, than anything else.

Trying to run any of the demo apps that come with the macOS download doesn't do anything (eg nothing is displayed).  Trying from the command line - hoping for useful info - gives this:

```
==========
VULKANINFO
==========

Vulkan Instance Version: 1.1.92

[***MoltenVK ERROR***] VK_ERROR_INCOMPATIBLE_DRIVER: Vulkan is not supported on this device. MoltenVK requires Metal, which is not available on this device.
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 0.  Skipping ICD.
Cannot create Vulkan instance.
/tmp/macos-sdk-build/Vulkan-Tools/vulkaninfo/vulkaninfo.c:835: failed with VK_ERROR_INCOMPATIBLE_DRIVER
```

Originally thought it was because I'm connecting to the box over VNC (!).  But it seems like the box is just too old, as the graphics card in it is a Geforce 320M.  Apparently Metal only support Keplar based Nvidia cards onwards, which came out a few years after the 320M. :wink:

Oh well. :man_shrugging:
